# Generated by Django 4.0.6 on 2022-07-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_post_tags'),
        ('categories', '0011_post_image'),
    ]

    operations = [
    ]
